use_frameworks!

target 'RecordVoicePlayer_Example' do
  pod 'RecordVoicePlayer', :path => '../'

  target 'RecordVoicePlayer_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
